### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by trijste** [msrch/obsidian-double-colon-conceal#1]
I linked to this from EK's roundup newsletter. I need help with how to install this. I downloaded the source, unzipped, copied it to my plugins folder, and restarted Obsidian. What do I need to include?

**Comment by msrch** [comment]
Hi, thanks for the question. I have added the install instructions to the [README](https://github.com/msrch/obsidian-double-colon-conceal#install) - copy pasted bellow for reference:

## Install

It is recomened to restart Obsidian after installing and enabling this plugin to prevent any render caching issues.

### Community Plugins in Obsidian

Not yet available - [review](https://github.com/obsidianmd/obsidian-releases/pull/1582/) pending.

In the mean time you can try this plugin using [BRAT - Beta Reviewers Auto-update Tester](https://obsidian.md/plugins?id=obsidian42-brat) - please follow [the instructions provided by BRAT repo](https://github.com/TfTHacker/obsidian42-brat#adding-a-beta-plugin).

### Manual installation

1. Download following files from the [latest release](https://github.com/msrch/obsidian-double-colon-conceal/releases/latest):
   - [`manifest.json`](https://github.com/msrch/obsidian-double-colon-conceal/releases/latest/download/manifest.json)
   - [`main.js`](https://github.com/msrch/obsidian-double-colon-conceal/releases/latest/download/main.js)
2. Go to plugins directory in your Obsidian vault - `{{vault-root}}/.obsidian/plugins`
3. Create new directory `obsidian-double-colon-conceal`
4. Put the `manifest.json` and `main.js` into the new directory  `{{vault-root}}/.obsidian/plugins/obsidian-double-colon-conceal`
5. Open Obsidian app and enable the "Double Colon Conceal" plugin in the "Community plugins" in the "Settings"
