### ISSUE TITLE
[BUG]Some emoticons and special characters don't remove double colon

### ISSUE THREAD

**Issue by OmniNaut** [msrch/obsidian-double-colon-conceal#2]
Hi,

I encountered that some emoticons and special characters don't remove the double colon in reading mode.
See screenshot for example. I did not test this through fully so it's probably likely that other emoticons and characters have the same behaviour.
In case of "Today's wins", I had to remove the hand emoticon and the apostrophe to solve the issue.
![image](https://user-images.githubusercontent.com/110312864/217145649-18b93b35-0bd2-4fe8-9612-46346641e186.png)

**Comment by msrch** [comment]
Hi thank you for reporting the issue. Could I ask you to post the source of your file from the screenshot to help me with debugging, please. Thank you

**Comment by OmniNaut** [comment]
Yes no problem man.
Here you go
[Daily template.md](https://github.com/msrch/obsidian-double-colon-conceal/files/10715784/Daily.template.md)

**Comment by msrch** [comment]
New version [1.1.4](https://github.com/msrch/obsidian-double-colon-conceal/releases/tag/1.1.4) got released with the fix. If you run into any other issues let me know. Thanks

FYI - the plugin got reviewed by the Obsidian team and is available in the Community Plugins registry so should be easier to install/update now.

![screenshot_20230212_113723](https://user-images.githubusercontent.com/5042903/218308864-93dcf7af-253e-464e-a28e-c39a4575307b.png)

**Comment by OmniNaut** [comment]
Can confirm it's fixed now.

Thanks 👍🏼
