### ISSUE TITLE
[FR] Also conceal - and _ in inline field

### ISSUE THREAD

**Issue by OmniNaut** [msrch/obsidian-double-colon-conceal#5]
As we know Dataview does not allow broken up fields. So for example having a field like Sleep Time would be preferable and nice to read. But not allowed.
The most common options to make it acceptable with dataview would be or: SleepTime, Sleep_Time or Sleep-time. For the last two options it would be nice if at least in the reading view the - and _ can be concealed. (And maybe there are other special characters to be considered which people use for the same purpose.

Although if you implement this than the name of the plugin does not cover the full capability anymore

**Comment by msrch** [comment]
Dataview allows field names with spaces - they get automatically normalized - https://blacksmithgu.github.io/obsidian-dataview/annotation/add-metadata/#field-names

In your example the `Sleep Time` can be accessed in Dataview query like:

- using the normlized name `this.sleep-time`
- or using the full name as well `this["Sleep Time"]`

![screenshot_20230411_115627](https://user-images.githubusercontent.com/5042903/231140367-a0663f73-f8cb-4836-894f-47670391f4a2.png)

Is this what you were referring to or is it different issue? In any case adding the ability to conceal the underscore or any other manipulation or concealment of characters in the Dataview field names is outside of scope of this plugin. If you need specific request in terms of functionality I would suggest sending feature request directly in the Dataview repo. Hope that makes sense and thanks for your interest in this plugin.

**Comment by OmniNaut** [comment]
My apologies, I was mistaken. I will look into this new information and hopefully it can reduce the complexity I had to build into my vault.

Thank you for pointing me in the right direction.
This issue can be closed
