### ISSUE TITLE
[FT] Option to replace the colon with another character

### ISSUE THREAD

**Issue by albertoloscerritos** [msrch/obsidian-double-colon-conceal#6]
Hi, thanks for the awesome plugin.
I think it would be a cool addition to have the option to select the character that is going to conceal the double colons. i.e. have the ability to change from `:` to `▞`  for example,  or any other selected UNICODE character.
Thanks.

**Comment by msrch** [comment]
Thanks for your interest. It is a good idea!

Changes in the new version [1.3.0](https://github.com/msrch/obsidian-double-colon-conceal/releases/tag/1.3.0):

- customize conceal character in the reading view
- customize conceal character in the editing view

![2024-06-17_11-57](https://github.com/msrch/obsidian-double-colon-conceal/assets/5042903/1e04e383-5042-4625-a708-345650b7a1ec)

If you find any issues, please let me know. Thanks

**Comment by albertoloscerritos** [comment]
Hi. I hope you are having a great Monday.
Thanks for the update. I am happy that you like the idea :)
